# Generated by Django 4.2.7 on 2023-12-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vendors DB model",
                "db_table": "vendor",
                "get_latest_by": "created_at",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="adresa_domiciliu_fiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ddenumire_Strada", models.CharField(max_length=100)),
                ("dnumar_Strada", models.IntegerField()),
                ("ddenumire_Localitate", models.CharField(max_length=100)),
                ("dcod_Localitate", models.IntegerField()),
                ("ddenumire_Judet", models.CharField(max_length=100)),
                ("dcod_Judet", models.IntegerField()),
                ("dcod_JudetAuto", models.CharField(max_length=100)),
                ("dtara", models.CharField(max_length=100)),
                ("ddetalii_Adresa", models.CharField(max_length=100)),
                ("dcod_Postal", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="adresa_sediu_social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdenumire_Strada", models.CharField(max_length=100)),
                ("snumar_Strada", models.IntegerField()),
                ("sdenumire_Localitate", models.CharField(max_length=100)),
                ("scod_Localitate", models.IntegerField()),
                ("sdenumire_Judet", models.CharField(max_length=100)),
                ("scod_Judet", models.IntegerField()),
                ("scod_JudetAuto", models.CharField(max_length=100)),
                ("stara", models.CharField(max_length=100)),
                ("sdetalii_Adresa", models.CharField(max_length=100)),
                ("scod_Postal", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="date_generale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cui", models.IntegerField(unique=True)),
                ("denumire", models.CharField(max_length=100, unique=True)),
                ("adresa", models.CharField(max_length=100)),
                ("nrRegCom", models.CharField(max_length=100, unique=True)),
                ("telefon", models.CharField(max_length=100)),
                ("fax", models.CharField(max_length=100)),
                ("codPostal", models.IntegerField()),
                ("act", models.CharField(max_length=100)),
                ("stare_inregistrare", models.CharField(max_length=100)),
                ("data_inregistrare", models.CharField(max_length=100)),
                ("cod_CAEN", models.CharField(max_length=100)),
                ("iban", models.CharField(max_length=100)),
                ("statusRO_e_Factura", models.BooleanField()),
                ("organFiscalCompetent", models.CharField(max_length=100)),
                ("forma_de_proprietate", models.CharField(max_length=100)),
                ("forma_organizare", models.CharField(max_length=100)),
                ("forma_juridica", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="extras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contactperson", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("web", models.CharField(max_length=100)),
                ("comments", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="inregistrare_RTVAI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataInceputTvaInc", models.DateField(max_length=100)),
                ("dataSfarsitTvaInc", models.DateField(max_length=100)),
                ("dataActualizareTvaInc", models.DateField(max_length=100)),
                ("dataPublicareTvaInc", models.DateField(max_length=100)),
                ("tipActTvaInc", models.CharField(max_length=100)),
                ("statusTvaIncasare", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="inregistrare_scop_Tva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scpTVA", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="inregistrare_SplitTVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataInceputSplitTVA", models.CharField(max_length=100)),
                ("dataAnulareSplitTVA", models.CharField(max_length=100)),
                ("statusSplitTVA", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="stare_inactiv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataInactivare", models.CharField(max_length=100)),
                ("dataReactivare", models.CharField(max_length=100)),
                ("dataPublicare", models.CharField(max_length=100)),
                ("dataRadiere", models.CharField(max_length=100)),
                ("statusInactivi", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PerioadeTVA",
            fields=[
                (
                    "inregistrare_scop_tva_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crm.inregistrare_scop_tva",
                    ),
                ),
                ("data_inceput_ScpTVA", models.DateField(blank=True, null=True)),
                ("data_sfarsit_ScpTVA", models.DateField(blank=True, null=True)),
                ("data_anul_imp_ScpTVA", models.DateField(blank=True, null=True)),
                (
                    "mesaj_ScpTVA",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            bases=("crm.inregistrare_scop_tva",),
        ),
        migrations.AddConstraint(
            model_name="date_generale",
            constraint=models.UniqueConstraint(
                fields=("cui", "denumire", "adresa", "nrRegCom"),
                name="dg_unique_constraint",
            ),
        ),
    ]
