# Generated by Django 4.2.7 on 2023-12-03 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_alter_vendor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "get_latest_by": "created_at",
                "managed": False,
                "verbose_name": "Vendors DB model",
            },
        ),
    ]
